### ISSUE TITLE
3 Different playbooks contains "cdi" role

### ISSUE THREAD

**Issue by gbenhaim** [kubevirt/kubevirt-ansible#298]
```
playbooks/cdi.yml:    - role: "cdi"
playbooks/kubevirt.yml:    - role: "cdi"
playbooks/storage.yml:    - role: "cdi"
```

Is this a bug?

**Comment by shiywang** [comment]
since `kubevirt-ansible` used as an upstream dependency for `kubevirt-apb`, so the `cdi` role in `playbooks/kubevirt.yml` was added due to that IIUC. and storage.yml also need `cdi` role, so I don't think it's a bug, also I tried deploy `cdi` multiple times, it seems like an "Idempotent" operate to me currently.

But my words doesn't count, so let @aglitke to chime in to give a more authoritative answer  : )

**Comment by aglitke** [comment]
CDI is now coupled with the kubevirt install so it should defintely be in kubevirt.yml.  We should remove it from storage.yml.  cdi.yml is a convenience playbook to help you deploy just cdi.  I don't think it is used by anyone but developers.  I would propose to keep it.
