### ISSUE TITLE
Don't disable the firewall of people which use kubevirt-ansible

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt-ansible#503]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

Don't disable selinux **and** the firewall by default if people install kubevirt on an k8s cluster. For as long as this is the case, please announce on as many places as you can that people should not use the playbooks here.

**What happened**:

A quick search revealed this: https://github.com/kubevirt/kubevirt-ansible/search?q=firewalld&unscoped_q=firewalld.

We don't have a feedback yet from the author of https://github.com/kubevirt/kubevirt/issues/1794 but it looks a lot like he used these playbooks.

**What you expected to happen**:

That the firewall and selinux stay enabled.

**How to reproduce it (as minimally and precisely as possible)**:

The playbook which disables these components is automatically executed in the default donfig: https://github.com/kubevirt/kubevirt-ansible/blob/d2c8d783423e8ba5c1dcc6e20873ab80363bbd41/playbooks/cluster/kubernetes/config.yml

**Anything else we need to know?**:

**Environment**:
- kubevirt-ansible version(use `git rev-parse HEAD`):
- KubeVirt version (use `virtctl version`):
- OpenShift/Kubernetes version (use `kubectl version` or `oc versions`):
- VM or VMI specifications:
- Ansible version  (use `ansible --version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fabiand** [comment]
To note: This is only an issue if kubevirt-ansible is used to deploy kubernetes or openshift with this playbook. IIUIC.

**Comment by fabiand** [comment]
@lukas-bednar @nellyc can we just remove the parts for openshift and kubernetes deployment from this playbook?

This would fix this bug.

**Comment by lukas-bednar** [comment]
@fabiand These playbooks are used by std-ci to perform testing. But I guess we could move these playbook under `automation/` directory at least and remove it from documentation.

**Comment by fabiand** [comment]
In general: With a company hat on, we just need to make sure that the
playbooks mimic what a user does if he follows the documented steps.
Otherwise we create a QE specific deployment path which does not tell us
what a user does.

For this paritcular bug: We need to clarify on this repository if this
inteded for production or not.
This bug would be an issue if you'd use this script for deployment in a
production environment.

Thus imo:

1. State clearly what this playbook is intended for
2. If this is for QE then we need to make sure that it mimcs what the
documentation says
3. All additional steps need to be filed as bugs to make sure they are
incorporated into the docs.
